name: HouCanBei
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.10.0
  - aom=3.6.1
  - appdirs=1.4.4
  - arabic_reshaper=3.0.0
  - astunparse=1.6.3
  - backoff=2.2.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.12.0
  - ca-certificates=2025.8.3
  - cairo=1.18.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - configobj=5.0.9
  - configparser=7.2.0
  - contourpy=1.3.2
  - cycler=0.12.1
  - dav1d=1.2.1
  - decorator=5.2.1
  - dukpy=0.5.0
  - esprima-python=4.0.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - freetype-py=2.5.1
  - fribidi=1.0.10
  - future=1.0.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gevent=25.5.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glfw=3.4
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.3.0
  - gnutls=3.7.9
  - gql=3.5.3
  - graphite2=1.3.14
  - graphql-core=3.2.6
  - greenlet=3.2.4
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - h2=4.2.0
  - harfbuzz=7.3.0
  - hdf5=1.14.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - imageio=2.37.0
  - imageio-ffmpeg=0.6.0
  - jasper=4.0.0
  - javascripthon=0.13
  - json_tricks=3.17.3
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.18
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.78.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.7.0
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=15.8
  - libprotobuf=4.23.2
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtasn1=4.20.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - moviepy=1.0.3
  - mpg123=1.32.9
  - msgpack-numpy=0.4.8
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nettle=3.9.1
  - nspr=4.37
  - nss=3.114
  - numexpr=2.10.2
  - numpy=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openpyxl=3.1.5
  - openssl=3.5.2
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.1
  - pathlib2=2.3.7.post1
  - pcre2=10.40
  - pillow=10.0.0
  - pip=25.2
  - pixman=0.46.4
  - ply=3.11
  - portaudio=19.7.0
  - proglog=0.1.10
  - propcache=0.3.1
  - psutil=7.0.0
  - psychopy=2022.2.5
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - py-opencv=4.7.0
  - pycparser=2.22
  - pyglet=1.5.27
  - pyglfw=2.9.0
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyobjc-framework-quartz=11.1
  - pyopengl=3.1.9
  - pyosf=1.0.5
  - pyparsing=3.2.3
  - pyqmix=2021.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyserial=3.5
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - pytables=3.8.0
  - python=3.10.0
  - python-bidi=0.6.6
  - python-dateutil=2.9.0.post0
  - python-gitlab=6.2.0
  - python-sounddevice=0.5.2
  - python-tzdata=2025.2
  - python.app=1.4
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - qt-main=5.15.8
  - questplus=2023.1
  - readline=8.2
  - requests=2.32.4
  - requests-toolbelt=1.0.0
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - scipy=1.15.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.50.4
  - svt-av1=1.4.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - webassets=2.0
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wxpython=4.2.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.6.1
  - xlrd=2.0.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zope.event=5.1.1
  - zope.interface=7.2
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - paranoid-scientist==0.2.3
      - pyddm==0.8.1
